### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by charlesaroutiounian** [parrot-flower-power/parrot-flower-power-api-example#1]
Issue with the Python Script, same thing when using CURL from the Terminal

Traceback (most recent call last):
  File "/Users/charlesaroutiounian/Downloads/parrot-flower-power-api-example-master/test_api.py", line 64, in <module>
    result = api_json('/user/v1/authenticate', {'grant_type':'password','client_id':client_id,'client_secret':client_secret,'username':username, 'password':password}, method='POST')
  File "/Users/charlesaroutiounian/Downloads/parrot-flower-power-api-example-master/test_api.py", line 39, in api_json
    result = urllib2.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by Stipend** [comment]
Hey Charles,  I work for Parrot and wanted to touch base on your issue.  I used your credentials on my account without issue. Could you retry and verify your account details.
